apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "helm-guestbook.fullname" . }}
  annotations:
{{- toYaml .Values.ingress.annotations | nindent 4 }}
  labels:
    app: {{ template "helm-guestbook.name" . }}
    chart: {{ template "helm-guestbook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "helm-guestbook.fullname" . }}
                port:
                  number: {{ .Values.service.port }}